let code1;
code1= 7+3;
const code2= 70 - 60 / 2;
const code3= (35 % 4) + 36;
const message= "The vault has been secured. The combination is:";
const codeA = code1 + "-" + code2 + "-" + code3;
const codeB = `${code1}-${code2}-${code3}`;
console.log(message);
console.log(codeA);
console.log(codeB);
